#!/usr/bin/env python3
"""
WHCA* fleet controller for Isaac Sim.

Receding-horizon execution of turn-aware WHCA* (Silver 2005) on a fleet of
namespaced differential-drive robots:

    every cycle:  read live poses from /robotN/tf
               -> plan one window with plan_window() (turn-aware, W//2 commit)
               -> each robot tracks its committed waypoints on a shared clock
               -> re-plan from real poses

Safety stack:
    1. Planning   — turn-aware WHCA*: plans are collision-free in space-time,
                    including rotation steps (WHCABaseline/whca_functions.py).
    2. Execution  — sequential waypoint tracking: robots visit exactly the
                    planned cells in order; the clock is a ceiling, never a
                    reason to skip cells. Sustained lag triggers an early re-plan.
    3. Safeguards — vacancy gate (don't enter a cell until physically clear)
                    and headway control (taper speed behind a slow robot).

Run (Windows, ROS-sourced pixi shell, Isaac playing with robots spawned):
    call C:\\pixi_ws\\ros2-windows\\local_setup.bat
    set ROS_AUTOMATIC_DISCOVERY_RANGE=LOCALHOST
    python whca_controller.py
"""
import rclpy
from rclpy.node import Node
from geometry_msgs.msg import Twist

import math
import os
import time
from collections import deque
import numpy as np
from tf2_msgs.msg import TFMessage
from PIL import Image

from whca_functions import plan_window, RRAstar
from positions import *

HERE = os.path.dirname(os.path.abspath(__file__))
MAP_YAML = os.path.join(HERE, "IsaacWarehouseOccupancyMapYAML.yaml")
CELL_SIZE = 1.0

WINDOW_SIZE = 32            # WHCA window W; commit/re-plan every W//2 steps
STEP_SECONDS = 1.9         # wall-clock length of one plan timestep (one cell
                           # traverse OR one 90-degree rotation)
LAG_REPLAN = 1.5           # re-plan early if any robot falls this many steps behind
DEADLOCK_CYCLES = 12       # stop if no robot has moved for this many windows

BASE_FRAME = "base_link"   # /tf: frame_id "world" -> this child frame = robot pose

# Drive controller
CONTROL_HZ = 20.0
ARRIVE_TOL = 0.18          # m: waypoint reached
ALIGN_TOL = 0.30           # rad: rotate in place until heading error below this
K_LIN, K_ANG = 1.2, 2.0
MAX_LIN, MAX_ANG = 0.6, 1.5

# Execution safeguards
# Clear radius is the distance (in meters) from the cell center that a robot must 
# be outside of # in order for another robot to enter the cell.  This is a bit larger
# than the robot's footprint to account for the fact that the robot may not be perfectly
# centered in the cell when it is moving through it. 
CLEAR_RADIUS = 0.635
# Headway is the distance (in meters) at which a robot will start to taper its speed to zero
# when it is behind another robot.
HEADWAY = 0.8
COLLIDE_DIST = 0.68

def load_map(yaml_path):
    """
        Load an occupancy map from a config file, as generated by the
        Isaac Sim occupancy map exporter.
        Returns a tuple: 
        (.yaml + image) -> (grid[x, y] 1=blocked, origin, cell).
    """
    
    cfg = {}
    # Read the YAML file
    with open(yaml_path) as f:
        for line in f:
            # Strip comments and whitespace
            line = line.split("#")[0].strip()
            
            # Extract key-value pairs from lines with a colon
            if ":" in line:
                k, v = (p.strip() for p in line.split(":", 1))
                cfg[k] = ([float(x) for x in v.strip("[]").split(",")]
                          if v.startswith("[") else v)
    
    # Extract variables from config file, with defaults for missing values
    image_name = cfg.get("image", None)
    negate = bool(int((cfg.get("negate", 0))))
    occupied_thresh = float(cfg.get("occupied_thresh", 0.65))
    res = float(cfg["resolution"])
    origin = [float(x) for x in cfg["origin"]]
    
    # Get path to occupancy map image
    img_path = os.path.join(os.path.dirname(yaml_path), image_name)
    
    # Load the image and convert to greyscale numpy array between 0.0 and 1.0
    arr = np.array(Image.open(img_path).convert("L"), dtype=np.float32) / 255.0

    # If negate value set, invert the occupancy values accordingly
    if negate:
        arr = 1.0 - arr
    
    # Determine which cells are occupied based on the threshold
    occupied = arr > occupied_thresh
    
    # Flip the occupancy grid so that the origin is at the bottom-left corner
    grid = np.flipud(occupied).T

    # Downsample the grid if the cell size is larger than the resolution
    f = max(1, int(round(CELL_SIZE / res)))
    if f > 1:
        w, h = (grid.shape[0] // f) * f, (grid.shape[1] // f) * f
        grid = grid[:w, :h].reshape(w // f, f, h // f, f).any(axis=(1, 3))
    
    # Return the occupancy grid, origin coordinates, and cell size   
    return grid.astype(np.uint8), origin[0], origin[1], f * res


GRID, ORIGIN_X, ORIGIN_Y, CELL_SIZE = load_map(MAP_YAML)
DIMX, DIMY = GRID.shape

# Save a visual representation of the occupancy grid for debugging purposes
Image.fromarray(GRID.T * 255).save(os.path.join(HERE, "isaacsim_map.png"))

# ------------------------------ small helpers ---------------------------------
def yaw_from_quat(x, y, z, w):
    """Convert quaternion to yaw"""
    return math.atan2(2.0 * (w * z + x * y), 1.0 - 2.0 * (y * y + z * z))

def wrap(a):
    """Wrap angle to [-pi, pi]."""
    return math.atan2(math.sin(a), math.cos(a))

def yaw_to_heading(yaw):
    """Snap yaw to grid heading 0=E, 1=N, 2=W, 3=S."""
    return int(round(yaw / (math.pi / 2))) % 4

def world_to_cell(wx, wy) -> tuple[int, int]:
    """Convert world coordinates to cell coordinates, clamped to grid bounds."""
    cx = int(round((wx - ORIGIN_X) / CELL_SIZE))
    cy = int(round((wy - ORIGIN_Y) / CELL_SIZE))
    return (min(max(cx, 0), DIMX - 1), min(max(cy, 0), DIMY - 1))

def cell_to_world(cx, cy) -> tuple[float, float]:
    """Convert cell coordinates to world coordinates, relative to origin."""
    return (ORIGIN_X + cx * CELL_SIZE, ORIGIN_Y + cy * CELL_SIZE)

def nearest_free(cx, cy, taken=frozenset()) -> tuple[int, int]:
    """BFS to the closest free cell not in `taken` (returns input if none found)."""
    q, seen = deque([(cx, cy)]), {(cx, cy)}
    while q:
        x, y = q.popleft()
        if GRID[x, y] == 0 and (x, y) not in taken:
            return (x, y)
        for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1)):
            n = (x + dx, y + dy)
            if 0 <= n[0] < DIMX and 0 <= n[1] < DIMY and n not in seen:
                seen.add(n)
                q.append(n)
    return (cx, cy)

def fmt_sched(cells):
    """Compact schedule string: only the timesteps where the cell changes."""
    out, last = [], None
    for t, c in enumerate(cells):
        if c != last:
            out.append(f"t{t}:{c}")
            last = c
    return " ".join(out)

class WHCAController(Node):
    def __init__(self):
        super().__init__("whca_fleet_controller")
        self.robot_ids = list(range(len(START_POSITIONS)))
        self.step_size = max(1, WINDOW_SIZE // 2)

        self.pose = {}                       # rid -> (x, y, yaw), live from /tf
        self.pubs = {}                       # rid -> /robotN/cmd_vel publisher
                
        for rid in self.robot_ids:
            self.pubs[rid] = self.create_publisher(Twist, f"/robot{rid}/cmd_vel", 10)
            self.create_subscription(TFMessage, f"/robot{rid}/tf",
                                     lambda m, r=rid: self._transform_subscriber(m, r), 10)

        self.goals: dict[int, tuple[int, int]] = None # rid -> goal cell (set once)
        self.rra: dict[int, RRAstar] = {}    # rid -> persistent RRAstar
        self.planning = True                 # True: plan next tick; False: executing
        self.waypoints = {}                  # rid -> committed world waypoints [0..W//2]
        self.progress = {}                   # rid -> last waypoint index reached
        self.sched_cells = {}                # rid -> committed cells (forensics)
        self.window_t0 = 0.0
        self.replans = 0
        self.stuck_windows = 0
        self.done = False
        self._contacts_logged = set()
        self._gate_log_t = 0.0

        self.create_timer(1.0 / CONTROL_HZ, self._tick)
        
        # Log map and robot info
        self.get_logger().info(
            f"Map {os.path.basename(MAP_YAML)}: {DIMX}x{DIMY} @ {CELL_SIZE:.2f} m, "
            f"{int(GRID.sum())} blocked. Robots {self.robot_ids}, "
            f"W={WINDOW_SIZE} (commit {self.step_size}).")

    def _transform_subscriber(self, msg, rid):
        """Update the robot's pose from its /tf message."""
        for tr in msg.transforms:
            if tr.child_frame_id == BASE_FRAME and tr.header.frame_id == "world":
                t, q = tr.transform.translation, tr.transform.rotation
                self.pose[rid] = (t.x, t.y, yaw_from_quat(q.x, q.y, q.z, q.w))
                return

    # ---------------- planning ----------------
    def _setup_goals(self):
        """One-time: fix each robot's goal cell (deduplicated) and its RRA*."""
        goals, taken = {}, set()
        for rid in self.robot_ids:
            # Find the nearest free cell to the robot's goal, avoiding already-taken cells            
            g = nearest_free(*world_to_cell(*ROBOT_GOALS[rid]), taken=taken)
            goals[rid] = g
            taken.add(g)

            # Compute the robot's RRA* for its goal, which is persistent across windows
            rra = RRAstar(g[0], g[1], GRID)
            self.rra[rid] = rra

        self.goals = goals
        self.get_logger().info(f"Goals: {sorted(goals.items())}")

    def _distinct_starts(self):
        """Current cells, made unique so the planner never gets two agents in one cell."""
        starts, taken = [], set()
        for rid in self.robot_ids:
            wx, wy, _ = self.pose[rid]
            c = nearest_free(*world_to_cell(wx, wy))
            # If the cell is already taken by another robot, find the nearest free cell
            if c in taken:
                c = nearest_free(*c, taken=taken)
            starts.append(c)
            taken.add(c)
        return starts

    def _plan(self):
        """Plan one window and commit the first W//2 steps as timed waypoints."""
        
        # Await connection to /tf topics for all robots before planning        
        if any(rid not in self.pose for rid in self.robot_ids):
            self.get_logger().warn("Waiting for all robots to publish /tf...")
            return False
        
        # If goals are not yet set, set them up now (one-time)
        if self.goals is None:
            self._setup_goals()

        # Get the current start cells for all robots, ensuring they are distinct
        starts = self._distinct_starts()
        
        # Check if all robots are already at their goals; if so, finish the controller
        at_goal = [s == self.goals[rid] for s, rid in zip(starts, self.robot_ids)]
        if all(at_goal):
            self._finish()
            return True

        # Silver-faithful planning:
        #  - EVERY agent plans every window, including agents at their goals
        #    (they plan zero-cost waits, but will step aside if a higher-priority
        #    agent needs their cell — no permanent parking).
        #  - Priority ROTATES each window (Silver 2005) so no fixed right-of-way
        #    pattern can repeat forever; this breaks symmetric deadlocks.
        n = len(self.robot_ids)
        
        # Rotate the priority order of robots for this planning window
        # TODO: implement random planning ordering
        rot = self.replans % n
        order = self.robot_ids[rot:] + self.robot_ids[:rot]
        
        idx = {rid: self.robot_ids.index(rid) for rid in order}
        
        self.get_logger().info(f"Planning order: {idx}")
        o_starts = [starts[idx[r]] for r in order]
        o_goals = [self.goals[r] for r in order]
        o_rra = [self.rra[r] for r in order]
        o_head = [yaw_to_heading(self.pose[r][2]) for r in order]

        t0 = time.perf_counter()
        o_paths = plan_window(o_starts, o_goals, GRID, WINDOW_SIZE,
                              [False] * n, o_rra, start_headings=o_head)
        dt_ms = (time.perf_counter() - t0) * 1000
        self.replans += 1
        paths = {rid: p for rid, p in zip(order, o_paths)}

        moved = 0
        for rid in self.robot_ids:
            path = paths[rid]
            by_t = {st.t: (st.x, st.y) for st in path}
            cells = [by_t.get(0, starts[self.robot_ids.index(rid)])]
            for t in range(1, self.step_size + 1):
                cells.append(by_t.get(t, cells[-1]))
                moved += cells[t] != cells[t - 1]
            self.sched_cells[rid] = cells
            self.waypoints[rid] = [cell_to_world(*c) for c in cells]
        self.progress = {rid: 0 for rid in self.robot_ids}
        self.window_t0 = time.monotonic()
        self.planning = False

        self.stuck_windows = 0 if moved else self.stuck_windows + 1
        if self.stuck_windows >= DEADLOCK_CYCLES:
            self.get_logger().error("No robot has moved for several windows — "
                                    "likely deadlock. Stopping.")
            self._finish()
        self.get_logger().info(
            f"[replan {self.replans}] {dt_ms:.1f} ms | commit {self.step_size} steps"
            f" | at goal {sum(at_goal)}/{len(at_goal)} | prio rot {rot}")
        return True

    # ---------------- execution safeguards ----------------
    def _cell_occupant(self, rid, tx, ty):
        """Another robot still physically inside the cell centred (tx, ty), or None."""
        for other in self.robot_ids:
            if other != rid and other in self.pose:
                ox, oy, _ = self.pose[other]
                if math.hypot(ox - tx, oy - ty) < CLEAR_RADIUS * CELL_SIZE:
                    return other
        return None

    def _gap_ahead(self, rid, wx, wy, tx, ty):
        """Distance to the nearest robot in a ~60-degree cone toward my target."""
        vx, vy = tx - wx, ty - wy
        vn = math.hypot(vx, vy)
        if vn < 1e-6:
            return None
        best = None
        for other in self.robot_ids:
            if other != rid and other in self.pose:
                dx, dy = self.pose[other][0] - wx, self.pose[other][1] - wy
                d = math.hypot(dx, dy)
                if 1e-6 < d <= HEADWAY and (dx * vx + dy * vy) / (d * vn) > 0.5:
                    best = d if best is None else min(best, d)
        return best

    def _check_contacts(self, plan_now):
        """Forensics: log full context on the first contact between any pair."""
        ids = [r for r in self.robot_ids if r in self.pose]
        for i in range(len(ids)):
            for j in range(i + 1, len(ids)):
                a, b = ids[i], ids[j]
                ax, ay, _ = self.pose[a]
                bx, by, _ = self.pose[b]
                d = math.hypot(ax - bx, ay - by)
                if d < COLLIDE_DIST and (a, b) not in self._contacts_logged:
                    self._contacts_logged.add((a, b))
                    self.get_logger().error(
                        f"CONTACT robots {a}&{b} d={d:.2f} m at plan_t={plan_now:.2f} "
                        f"(replan #{self.replans})\n"
                        f"  r{a}: at {world_to_cell(ax, ay)}, "
                        f"sched={fmt_sched(self.sched_cells[a])}\n"
                        f"  r{b}: at {world_to_cell(bx, by)}, "
                        f"sched={fmt_sched(self.sched_cells[b])}")

    # ---------------- control loop ----------------
    def _tick(self):
        if self.done:
            return
        if self.planning:
            self._plan()
            return

        plan_now = (time.monotonic() - self.window_t0) / STEP_SECONDS
        self._check_contacts(plan_now)
        due = min(int(plan_now) + 1, self.step_size)   # furthest step the clock allows
        max_lag = 0

        for rid in self.robot_ids:
            if rid not in self.pose:
                continue
            wx, wy, yaw = self.pose[rid]
            prog = self.progress[rid]
            max_lag = max(max_lag, due - prog - 1)
            target = min(prog + 1, due)                # next waypoint only, never skip
            tx, ty = self.waypoints[rid][target]
            dist = math.hypot(tx - wx, ty - wy)
            cmd = Twist()

            if dist < ARRIVE_TOL:                      # at waypoint
                if target > prog:
                    self.progress[rid] = target
                self._pre_rotate(rid, wx, wy, yaw, cmd)   # planned rotation step
                self.pubs[rid].publish(cmd)
                continue

            occ = self._cell_occupant(rid, tx, ty)
            if occ is not None:
                # STRICT vacancy gate: never enter a cell while any robot is
                # physically inside it, regardless of whether it plans to leave.
                now = time.monotonic()
                if now - self._gate_log_t > 2.0:
                    self._gate_log_t = now
                    self.get_logger().warn(
                        f"vacancy gate: r{rid} holding for r{occ} in "
                        f"{world_to_cell(tx, ty)}")
                self.pubs[rid].publish(cmd)
                continue

            hd = wrap(math.atan2(ty - wy, tx - wx) - yaw)
            if abs(hd) > ALIGN_TOL:                    # face the cell first
                cmd.angular.z = max(-MAX_ANG, min(MAX_ANG, K_ANG * hd))
            else:                                      # drive, with headway taper
                fwd = max(0.0, min(MAX_LIN, K_LIN * dist))
                gap = self._gap_ahead(rid, wx, wy, tx, ty)
                if gap is not None:
                    fwd = min(fwd, MAX_LIN * max(0.0, (gap - 0.6) / (HEADWAY - 0.6)))
                cmd.linear.x = fwd
                cmd.angular.z = max(-MAX_ANG, min(MAX_ANG, K_ANG * hd))
            self.pubs[rid].publish(cmd)

        window_done = all(self.progress[r] >= self.step_size
                          for r in self.robot_ids if r in self.pose)
        if (plan_now >= self.step_size and window_done) or max_lag > LAG_REPLAN:
            self.planning = True                       # re-plan from real poses

    def _pre_rotate(self, rid, wx, wy, yaw, cmd):
        """During a planned rotation/wait step, pre-align toward the next new cell."""
        for wp in self.waypoints[rid][self.progress[rid] + 1:]:
            if math.hypot(wp[0] - wx, wp[1] - wy) > ARRIVE_TOL:
                hd = wrap(math.atan2(wp[1] - wy, wp[0] - wx) - yaw)
                if abs(hd) > 0.08:
                    cmd.angular.z = max(-MAX_ANG, min(MAX_ANG, K_ANG * hd))
                return

    def _finish(self):
        self.done = True
        for rid in self.robot_ids:
            self.pubs[rid].publish(Twist())
        self.get_logger().info(f"Done. Total re-plans: {self.replans}.")


def main():
    rclpy.init()
    node = WHCAController()
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        try:
            # Stop all robots on exit
            for rid in node.robot_ids:
                node.pubs[rid].publish(Twist())
        except Exception:
            pass
        node.destroy_node()
        rclpy.shutdown()


if __name__ == "__main__":
    main()
